### ISSUE TITLE
"mods/medals/halo3.zip" has failed to download

### ISSUE THREAD

**Issue by emoose** [ElDewrito/ElDorito#1]
Making this an open issue so more people see it... just make a new folder in your HO dir called mods, and make a new folder inside there called medals, then rerun the updater.

Once we push a fixed updater properly I'll close this issue.

**Comment by Shad0wShayd3** [comment]
If you come onto IRC to ask about this, I will probably kill you.

**Comment by emoose** [comment]
+1

**Comment by DEElekgolo** [comment]
![orz](https://cloud.githubusercontent.com/assets/644247/8324451/98c600fe-1a05-11e5-8aba-c504b7d5b44c.gif)

**Comment by 101ways2pwn** [comment]
Really dude? Really?

**Comment by vicelio** [comment]
This is no longer an issue. That affected launcher has been completely obsoleted.
