### ISSUE TITLE
I can't use Eldewrito Launcher

### ISSUE THREAD

**Issue by Zephyritz** [ElDewrito/ElDorito#106]
Whenever I run the latest edition of DewritoLauncher(which I downloaded from eldewrito.com)
, It crashes. I deleted my entire directory and tried to re-download it via Launcher it can't because it crashes! I tried an older version to try to download, It just gets to the Verifying part and it crashes!
I can't play Halo Online anymore so I need help urgently!!
Please HELP!!!!

**Comment by FishPhd** [comment]
this was an update server issue that has been resolved

**Comment by Zephyritz** [comment]
Could you please maybe give a little tutorial as to how to fix it?
Sorry I'm disturbing you on Reddit as well as this but as you can see I'm really desperate on getting HO to work again.
Thanks a million!

**Comment by FishPhd** [comment]
Download launcher or files from here http://eldewrito.com/ now that update server is up the launcher should run properly.
