### ISSUE TITLE
Gameoverlays Don't work (E.g. Steam,Overwolf, AMD Gaming evolved)

### ISSUE THREAD

**Issue by PersonalityPi** [ElDewrito/ElDorito#11]
Gameoverlays don't seem to want to work anymore. (I'm guessing this is related to the directxhook stuf)

**Comment by maximumgame** [comment]
Working fine for me with steam overlay. 
![overlay](https://cloud.githubusercontent.com/assets/3354564/8397725/f586ca44-1da2-11e5-86b7-f7067d24931a.PNG)

**Comment by vicelio** [comment]
@maximumgame What build is that? I see irc loop errors.

**Comment by maximumgame** [comment]
@vicelio I just cloned the repo and built it about 5 minutes ago.

**Comment by vicelio** [comment]
@maximumgame Can you try the below steps?

1. Delete dorito.log in your halo folder
2. Put this build in your halo folder https://d.maxfile.ro/qiiuujdtxu.dll (rename to mtndew.dll)
3. Run the game once and let it attempt to connect 3 times. Exit the game.
4. Upload dorito.log

**Comment by maximumgame** [comment]
@vicelio I figured it out. Invalid username since I was using <time_hms/> as the name.

The log is here anyway though http://pastebin.com/gMupvpet

**Comment by vicelio** [comment]
@maximumgame Weird that it would give an invalid username. What username did you select?

**Comment by maximumgame** [comment]
@vicelio It was <time_hms/> I use it because in the lobby it makes your username the local time of the person who views it.

**Comment by yolarrydabomb** [comment]
I got a idea. can you make the game to load steam overlay and tell your steam friends you playing in-mod or in-game eldorito?

**Comment by LordOfGears2** [comment]
Steam Overlay works great for me

**Comment by PersonalityPi** [comment]
Our of curiosity those people using steam overlay are you on nvidia or AMD

**Comment by PersonalityPi** [comment]
Okay checked with a few different people it seems related to AMD. Doesn't seem to affect anyone on nvidia (Same problem that happens with the htmlmenu btw)
