### ISSUE TITLE
Eldewrito - Current Version: Error

### ISSUE THREAD

**Issue by Cencil182** [ElDewrito/ElDorito#111]
Hi. I followed the instructions to get this set up on the website word for word. I'm getting an error when I hit update after it attempts to download files, within seconds the download progress window closes and brings me back to the launcher saying "Error" where the update/play button should be. I've tried restarting, running as admin, uninstalling ALL anti virus software. I'm running Windows 10 if that helps.

Any ideas?

**Comment by Shockfire** [comment]
Please post launcher-related issues at https://github.com/FishPhd/DewritoUpdater/issues
