### ISSUE TITLE
Raw Input

### ISSUE THREAD

**Issue by Squish8294** [ElDewrito/ElDorito#112]
Enabling Raw Input in the game launcher forces mouse Y Axis inversion for me. Unknown reason why. Inverting in settings in game correctly inverts, but does not undo raw input inversion.

**Comment by MikeRavenelle** [comment]
I am going to look into this, seems like there is a possibility of setting it in the cfg file for a temporary fix.

**Comment by MikeRavenelle** [comment]
I was unable to replicate this issue. Inversion is correct with raw input set to true. Checked the cfg file and is showing correctly. No in game settings changed.

**Comment by Squish8294** [comment]
I'll drop a video of it in a bit onto youtube so you can see it.
