### ISSUE TITLE
G-Sync

### ISSUE THREAD

**Issue by LukeJHarvey** [ElDewrito/ElDorito#116]
I don't know how much you can do, but if you have G-Sync enabled it makes the game begin to glitch out hardcore with everything. Framerate drops to 20 and stays there. If you could add G-Sync support somehow that would be nice, but if not it's all good, it would just be nice if there was a warning somewhere. Thanks.

**Comment by Shockfire** [comment]
There's nothing we can do about this. Your best bet is to just disable it for this game in Nvidia Control Panel. I could ask to get it added to the FAQ on reddit.
