### ISSUE TITLE
Keys stuck after opening console

### ISSUE THREAD

**Issue by ghost** [ElDewrito/ElDorito#12]
"if you press ctrl while not in chat and then open chat, even after releasing ctrl and press v it pastes the clipboard"

Need to get rid of the raw input hook but to do that, I need to find a proper way to disable game keyboard input

**Comment by dark-c0de** [comment]
This is also an issue when holding in W (to move forward) and then hitting the console key. You will continue to move forward, even after you close the console window.

**Comment by amd7** [comment]
f4bbc1aed5d6642c2516e93fbb0f0c08e6068738 fixes both of these issues.

**Comment by ElDewritoDev** [comment]
f4bbc1aed5d6642c2516e93fbb0f0c08e6068738 fixes both of these issues.
