### ISSUE TITLE
Player Spectator Camera Issues

### ISSUE THREAD

**Issue by Kashikoii** [ElDewrito/ElDorito#139]
If a player dies and has no lives left, the camera is locked at a certain angle and can only sometimes rotate with "a" and "d" keys. Sometimes players can switch who they're spectating but it's inconsistent; often players are left staring at their dead bodies until the round ends. I'm guessing the camera is stuck at a particular Y coordinate and there isn't a key mapped to adjust it, but that's just an idea.

This makes playing many gamemodes such as jenga very unenjoyable.

**Comment by theTwist84** [comment]
Don't worry this has been fixed in a recent commit.
