### ISSUE TITLE
Game Not Saving Settings/Name

### ISSUE THREAD

**Issue by Smelly-Potato** [ElDewrito/ElDorito#140]
I recently downloaded ElDewrito 0.5.0.2 and I am having troubles customizing my spartan. First off I set my name in the launcher settings and every time I start the game, I get a random name. Second, I can't seem to change the video settings. Once the game starts, the settings revert back to default and when I change them during the game, I don't notice anything different. Is there something that I'm not doing right? 

Thanks,
    Smelly-Potato

**Comment by Red-M** [comment]
Launcher related issues will need to go to the launcher developer.
As for the other issues I am unsure.

**Comment by FishPhd** [comment]
https://github.com/FishPhd/DewritoUpdater
