### ISSUE TITLE
Can't join servers

### ISSUE THREAD

**Issue by Soupah** [ElDewrito/ElDorito#142]
I can't join server. Whenever I click on a server to connect nothing happens, I can only join servers when they're in the lobby. I tried turning off my firewall and anti virus but it still won't let me.

Also on the map sandtrap it's like the brightness is way too high. All I see is a white screen. 
![white screen of bugtown](https://cloud.githubusercontent.com/assets/17931560/13883886/7caa8be8-ecf9-11e5-8a58-3afb2f39ac12.PNG)

**Comment by Yppiti** [comment]
These are two issues. I suggest opening a separate issue for the map and one for server issues. What happens? Is this one specific server? This sounds more like an issue with your network configuration than the code itself.

Are you able to launch the game in "Host Forge" or "Host Multiplayer"? The fact that I see a score on two teams in that screenshot tells me this is a network misconfiguration.

**Comment by scooterpsu** [comment]
There are also some of the dedicated servers (specifically those hosted by G-Money) that people have issues joining while in progress. This is an issue on _his_ end, not yours. If it is happening with all servers, that is a network issue on _your_ end.

The brightness (which yes, is a second issue), can usually be sorted by disabling any processing done by the nVidia control panel (if an nVidia gpu, obviously). If it persists, or is a different gpu, let us know.

Issues like this are usually best sorted on the [subreddit ](https://www.reddit.com/r/HaloOnline/)(or the [IRC](http://irc.lc/snoonet/eldorito/#irc) if you need any one-on-one assistance), as every comment emails everyone watching the project (48 people currently).
