### ISSUE TITLE
Flood filter for in-game chat

### ISSUE THREAD

**Issue by Shockfire** [ElDewrito/ElDorito#153]
We received a suggestion to add a server-side flood filter to in-game chat in order to cut down on people spamming during games. I think this would be a good idea.

Some things to consider:
* A dampening effect. If a client sends X amount of messages within Y seconds, start a timer and reject messages until the timer expires. Double/increase the timeout delay for repeat offenses.
* Add a client-side delay that waits to send a message if a message was sent shortly before it (the server-side flood limit should still be longer than this though).
* Allow hosts to enable or disable this feature with a variable.

Implementation details:
* None of this should apply to the host (obviously).
* Timeout can be on a per-peer basis to make things simple (just store info in a global fixed-size array). The only caveat to this is that a peer's timeout needs to be reset on disconnect and we don't have an event for that (unfortunately). Perhaps loop through all of the connected peers each tick and reset the timeouts of peers that aren't visited.
* Timeout checking code can be added to the HostReceivedMessage function at https://github.com/ElDewrito/ElDorito/blob/master/src/Server/ServerChat.cpp#L173
* If a message is rejected due to a timeout, the client should be sent a message indicating this.

Community contributions for this are welcome - just send a pull request to the master branch (and maybe reply to this before you start so that others are aware). Do note that I might be making some changes to the chat system sometime soon in order to make it easier to bind to the web-renderer UI, but it will be nothing major and I can handle fixing up code to work with it myself. (Mainly just making it easier to detect which player sent a message so that we can show team colors etc.)

**Comment by AstonWaters** [comment]
Adding to this suggestion, I think it would be beneficial for hosts to be able to server-wide mute individuals from chat.

**Comment by Shockfire** [comment]
>Adding to this suggestion, I think it would be beneficial for hosts to be able to server-wide mute individuals from chat.

Oh yeah, definitely. Probably would be a good idea to do it on a per-IP basis. Maybe the banning system can be expanded to allow for different categories of bans (chat, voice, global, etc.).

**Comment by AstonWaters** [comment]
That would be great.  Since you mentioned it, a host ability to mute an individual from voip would also be great, but I didn't say anything because I know voip is getting worked on already.  

And why not add one more related wish of mine...  the ability to add comments while banning/muting/etc.  Some ban offenses are worse than others.  I like to clear my ban list every so often, but there are some people who deserve a perma-ban.  Unless I manually notate it, I can't tell who deserves a second chance and who does not.

**Comment by Shockfire** [comment]
Well I'm going to start working on this and then release just this as a 0.5.0.3 update. [Things have gotten pretty bad](https://www.reddit.com/r/HaloOnline/comments/4dlv8d/we_need_to_do_something_about_the_halo_ce_spammers/).

**Comment by AstonWaters** [comment]
It's bad for those dedi's because people aren't easily kicked.  From that screenshot, someone started a votekick and needs 8 more people to put it through.  I've been in those games and some people just don't vote.  A chat spammer in a moderated game would be banned super fast.  #dediproblems

**Comment by Shockfire** [comment]
Vote kicking in this case is probably even harder to pass since it's done via chat and a spammer can very quickly make the notification go off of the screen. Also it might be a bit inconvenient because I think it's set up so that you have to enter a response into the chatbox in order to vote. I know that some games let you vote by just pressing a key. It might be possible to improve the system with 0.6. We'll have the new UI stuff, and RabidSquabbit is part of the team now so we can merge his code in.

**Comment by Red-M** [comment]
You're meant to use shotguns or fire on the flood.
