### ISSUE TITLE
Missing file when I download

### ISSUE THREAD

**Issue by PEGADERP** [ElDewrito/ElDorito#156]
### Guidelines
- Your title should clearly describe the issue.
- Describe the exact steps you took before the problem arose.
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link).

### I don't know how i got this problem

1.I run my computer on windows ten if that helps

2.I tried to download through everything but torrent

**Comment by maximumgame** [comment]
Run "directx_june2010.exe" found inside the /tpi/directx folder.

**Comment by PEGADERP** [comment]
nothing happened
