### ISSUE TITLE
{FORGE} Suggestion

### ISSUE THREAD

**Issue by LukeTCThatsMe** [ElDewrito/ElDorito#157]
So I make a lot of maps for HO, is it possible to have "Read Only" forge maps where I send them out for other people to play but they cant edit them. I have people re-releasing different versions of my maps they have slightly edited which then is under their name. And if not, could you keep the original authors name when they first create the map even if someone else changes it?

**Comment by theTwist84** [comment]
No

**Comment by medsouz** [comment]
We don't have very much control over the Forge file format right now. Making a change like this would take up development time and potentially break older Forge maps.

If you're having issues with people ripping off your stuff I recommend you contact the admins where it was posted (NoShotz on Reddit or qmarchi on HaloCafe) and ask them to take it down.
