### ISSUE TITLE
Keyboard Mappings Reset on Game Launch

### ISSUE THREAD

**Issue by Yppiti** [ElDewrito/ElDorito#162]
**What were you trying to do before the issue occurred?**

- Play using previously mapped controls.

**What happened?**

- Some mappings reset to default (in this case, grenade throw, melee) when the game is launched. Have to go back in and simply press "save" - the mappings all show the correct entries but are not applied until "save" is pressed in control mappings after relaunching game.

**What did you expect to happen?**

- Controls to stay in the state they were last saved.

**How can the issue be reproduced?**

1. Set keyboard mapping MELEE to MIDDLE MOUSE SCROLL
2. Set keyboard mapping GRENADE THROW to LEFT CTRL
3. Save settings.
4. Completely close client, launcher and any processes left in memory.
5. Launch the game and play a match, attempt to use controls mapped.
6. Go into custom mapping and simply press "save" controls and exit in game menu. Controls restored.

**Comment by NoShotz** [comment]
This is already fixed for version 0.6.0

**Comment by scooterpsu** [comment]
This is a known issue with the built in binding system. It was solved with https://github.com/ElDewrito/ElDorito/commit/44089ddfd49829168d39f392fd63883f90a88a5d.
