### ISSUE TITLE
Delete this

### ISSUE THREAD

**Issue by RustyCanadian** [ElDewrito/ElDorito#172]
# THIS IS NOW IRRELEVANT AND CAN BE DELETED

### Guidelines
  Can't run the game with the complied mtndew.dll. ;

  When I open it in Microsoft Visual Studio the version 0 . 6 . 0 . 0 Always have to change it for current version ( 0 . 5 . 1 . 1 ) ; --> VS_VERSION_INFO

  Missing the .bat Generator ( generate_vs2013_sln_files.bat ) ;

### What were you trying to do before the issue occurred? 
  Looking for issues, trying my best to learn 

### What happened?
  Game doesn't work with the mtndew.dll made from this github, version is wrong for me and have to change it otherwise it's saying wrong version and I can't join games. With fixed version, game doesn't boot (no mods installed all CLEAN and NEW game install). 

### What did you expect to happen?
  at least a working version of the build? I respect the guys behind it for sure but why is it not working for me?

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Just download and compile this version? Not sure why it's doing this... Email: Callisto89@live.ca

2.

3.

**Comment by NoShotz** [comment]
You are most likely missing dependancies, why are you trying to build it anyways?

**Comment by NoShotz** [comment]
Also, you can not build a 5.1.1 dll from here unless you use the 5.1.1 branch

**Comment by RustyCanadian** [comment]
I just figured it out, I was in the wrong branch... Thank you!

This can be deleted sorry for missing the branch...

**Comment by medsouz** [comment]
Did you read this at all? https://github.com/ElDewrito/ElDorito/blob/master/src/Utils/VersionInfo.cpp#L12

**Comment by scooterpsu** [comment]
Rather than the rename, next time just close it yourself.
