### ISSUE TITLE
Problem with the resolution

### ISSUE THREAD

**Issue by Julianty123** [ElDewrito/ElDorito#176]
### Guidelines
- Your title should clearly describe the issue. Problem with the resolution
- Describe the exact steps you took before the problem arose. I go to settings and try to change the resolution, but i cant. 
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link). 

The resolution max possible is 1366 x 768, i have a laptop with resolution FULL HD (1920 x 1080). But evertheless the game it does not let me put the resolution max (full hd) i dont know why, also i have two graphics cards (Intel HD Graphics 4600 & NVIDIA GeForce GTX 960M)
### How can the issue be reproduced?

Please be as descriptive as possible.

1.

2.

3.

**Comment by NoShotz** [comment]
Please read the known issues page on the wiki for a fix https://www.reddit.com/r/HaloOnline/wiki/knownissues

Also, try to use the issue formatting better next time.

**Comment by Julianty123** [comment]
Ok..

**Comment by medsouz** [comment]
Have you tried disabling DPI scaling on eldorado,exe?

**Comment by wub** [comment]
There's recently been a commit to make the app DPI aware - try again when 0.6.0 comes out.

**Comment by medsouz** [comment]
Whoops I forgot to close this.

Resolved by https://github.com/ElDewrito/ElDorito/commit/22059e234c40dc01cdb68448f09e3b0a3ab62477
