### ISSUE TITLE
RCON needs to be password-protected

### ISSUE THREAD

**Issue by Shockfire** [ElDewrito/ElDorito#178]
This shouldn't be too difficult for a community member to work on and it would have a pretty high impact, so I'm opening this issue report.

Currently, the websocket RCON system is not password-protected. This poses a major security problem because any website that you load in your browser could connect to your game and read or write console variables. It's also a huge inconvenience for server owners, because if you leave the port open then anyone can take control over your server.

**Here is our current plan for improving the security of the RCON system:**
- There will be a `Server.RconPassword` variable which allows server owners to set a password.
- If the `Server.RconPassword` variable is not set when the game starts (i.e. it is an empty string), then a long (16+ chars) password should be randomly-generated at uniform and saved to the variable. The voip-rewrite branch has a [Utils::Cryptography::RandomBytes function](https://github.com/ElDewrito/ElDorito/blob/voip-rewrite/src/Utils/Cryptography.cpp#L175) which should be used for this.
- The first line that is sent over a websocket will be interpreted as the password. If it does not match the `Server.RconPassword` variable, then the client should be disconnected.

While this will break any existing apps which use RCON, it should be very easy for developers to update their apps to require a password. The security improvements that this change offers far outweigh any negatives that we can see.

**Relevant code:**
- RCON command execution: https://github.com/ElDewrito/ElDorito/blob/master/src/Patches/Network.cpp#L151
- RCON initialization: https://github.com/ElDewrito/ElDorito/blob/master/src/Patches/Network.cpp#L463
- Server module: https://github.com/ElDewrito/ElDorito/blob/master/src/Modules/ModuleServer.cpp

If you're interested in working on this, then leave a comment here so that others know, otherwise we'll get to it at some point before 0.6 releases.

**Comment by maximumgame** [comment]
I can take a stab at it.

Seems there are two rcon servers running, one on port 2448 which desktop apps are using and another using websockets on 11776 for webpages.

https://github.com/ElDewrito/ElDorito/blob/master/src/ThirdParty/WebSockets.cpp

Should the RandomBytes function be copied from voip-rewrite to be merged with master or should the patch be built off the voip-rewrite branch?

Should the password be clamped to valid ascii characters or just cast the random bytes to char no matter what they are?

**Comment by medsouz** [comment]
> Should the RandomBytes function be copied from voip-rewrite to be merged with master or should the patch be built off the voip-rewrite branch?

I would copy it over to master

> Should the password be clamped to valid ascii characters or just cast the random bytes to char no matter what they are?

Keep it valid ASCII
