### ISSUE TITLE
Forceload command issue (locale?)

### ISSUE THREAD

**Issue by Tillice** [ElDewrito/ElDorito#183]
Using strings while forceloading gamemodes doesnt work, it just forceloaded none none (0 0) instead
<img src="http://i.imgur.com/5VTN30C.png" />
was talking to camden, and according to him it seems like it'd be a locale issue

**Comment by maximumgame** [comment]
Survival isn't a valid gamemode. You have a choice between:

none
campaign
multiplayer
mainmenu
shared

Anything else seems to default to no gametype and no gamemode.

**Comment by Tillice** [comment]
was talking with a developer during the time i was writing this issue, and it seemed to be the only valid reason for the error. since it worked fine on his machine (he sent the same dll build my way)

**Comment by scooterpsu** [comment]
Survival uses campaign, so this isn't a bug.
