### ISSUE TITLE
Replace teamspeak voice with Discord

### ISSUE THREAD

**Issue by brodycas3** [ElDewrito/ElDorito#198]
I feel like this would be a better alternative to shoddy teamspeak code.

https://discordapp.com/gamebridge
https://discordapp.com/developers/docs/topics/gamebridge

**Comment by maximumgame** [comment]
Discord's gamebridge sdk is only being handed out to people that Discord accepts in to their program currently. As such the sdk is not publicly available. I do not think Discord would want an open source project to use their sdk at this time.

Also, using their sdk requires us to follow their guidelines on ui design that may not stay consistent with our own ui.

And finally, if discord ever disappears their will be no voip support at all.

Teamspeak has already been removed and replaced with a new system that is p2p and should work in the future. As long as google and firefox's public turn servers continue to exist it should work. If for some reason they do not, the servers can easily be changed.

**Comment by brodycas3** [comment]
Then if that's the case I'll close this.
