### ISSUE TITLE
Game.ShowUI does nothing.

### ISSUE THREAD

**Issue by shad0wshayd3** [ElDewrito/ElDorito#20]
Both the Game.ShowUI and show_ui have no function in newer builds of Eldorito, Presumably this happened after the console was integrated into the game, I don't have enough old builds to verify. But it did work before the console was integrated, and it doesn't now.

**Comment by 101ways2pwn** [comment]
Same here.. in game GUI is now gone.
Commit: f40a7d339a3b76a4c2dcddaf7a8d43a553174acc
Build: 0.4.7.0
Date of build: 7/2/2015

Graphics Card: Nvidia GTX 980
DX9 Extensions enabled

**Comment by Alex-231** [comment]
The syntax changed I think. Works for me anyway. Try show_ui 0x100d3 on the mainmenu map.

**Comment by Shockfire** [comment]
This command needs to be removed...it's really useless nowadays and doesn't even load most dialogs properly.

**Comment by Alex-231** [comment]
Pleeeaaase don't remove it, It's not doing any harm.

**Comment by Alex-231** [comment]
Also doesn't this need closing?
