### ISSUE TITLE
Error: Cannot Connect to Eldewrito

### ISSUE THREAD

**Issue by perfectlylegit24** [ElDewrito/ElDorito#209]
I was simply trying to play the game but for some reason my eldorado won't connect to ElDewrito. I have done nothing with any mods never even played a halo game before. All of a sudden, for some reason, my game has stopped letting me hook up to servers telling me it can't connect to Eldewrito. I don't know how or what is happening, much less how to replicate it. I haven't changed any settings aside from my FOV and crosshair placement, moving it to the center in the settings menu. I let the game through my firewall, so what did I do wrong?

**Comment by scooterpsu** [comment]
The error saying it can't connect to ElDewrito is an issue between the browser and the game itself. The connection method is buggy (and was replaced for the 0.6 update). See if you get the issue joining from your web browser instead from http://scooterpsu.github.io (be sure to whitelist it for an adblocker if you use one).
