### ISSUE TITLE
Duplicated objects from Clients in Forge do not replicate to Server

### ISSUE THREAD

**Issue by ThiconZ** [ElDewrito/ElDorito#212]
### Version
0.6.0.0-dev (Latest Master)

### What happened?
When a Client duplicates an object in Forge, it will not replicate to the Server. The Client is then unable to pickup the duplicated object, delete the duplicated object, or interact with it in Player mode. On the Server side it appears as if nothing is there.

### What did you expect to happen?
If a Client duplicates an object it is properly replicated to the Server.

### How can the issue be reproduced?

1. Create an online Forge session with at least one Client on any map.

2. Have a client duplicate an object (Press C by default while looking at once).

3. Observe as the Server that the object does not appear.

**Comment by scooterpsu** [comment]
This is actually expected behavior, as the command only works for the host (the engine just doesn't support the creation of that many items remotely at once).

Before release, the command will be changed to host-only.
