### ISSUE TITLE
Cannot play game using the Eldewrito Launcher

### ISSUE THREAD

**Issue by labrat14** [ElDewrito/ElDorito#218]
The game will not play and will only have the loading icon when clicking "play game" on the launcher. I have tried to uninstall and reinstall the files using both regular and torrent downloads from the site. I have removed the preferences.dat file several times. I have tried running it in Admin with previous steps. I even tried to download previous build and update. Nothing works.

**Comment by PersonalityPi** [comment]
Hey, try to make a shortcut of eldorado.exe and add -launcher to the launch parameters.

**Comment by labrat14** [comment]
That does nothing. Just in case, I did the same with the updater.

**Comment by Red-M** [comment]
When you say it does not play, do you mean it does not start from the launcher or it does not start the launcher?

**Comment by labrat14** [comment]
When I start the launcher and customize the setting or leave it alone, then hit "play-game". It loads then does nothing.

**Comment by Red-M** [comment]
So it starts and you can't get to the main menu?

**Comment by labrat14** [comment]
The launcher starts. I hit play and then nothing.

**Comment by Red-M** [comment]
Can you see if the process is still running in task manager?

**Comment by labrat14** [comment]
No process in task manager.

**Comment by labrat14** [comment]
I will make this specific. When I launch the updater. I customize my settings for my weapons and armor to my liking and when I am done I click, "play game". When I click that, the mouse cursor loads like it is going to play the game, but does nothing.

**Comment by labrat14** [comment]
This is a real turn-off because I am a new player and have yet to play.

**Comment by Red-M** [comment]
What version of windows do you have, what GPU, what CPU.

**Comment by labrat14** [comment]
- Windows 10. 
- I am on a laptop. 
- Intel Graphics 620/Geforce 940mx (according to gd hardware) 
- Core I7-7500U 2-core 2.7 GHz

**Comment by scooterpsu** [comment]
Github issues are more for code issues, not support. Please use either the Discord or subreddit, both linked on the readme (and copied below).

## Help/Support/Contact
We have a [Discord server](https://discord.gg/halo) that stays pretty active with helpful users.
You can also try checking the support question on the [subreddit](https://www.reddit.com/r/HaloOnline/).

**Comment by labrat14** [comment]
That is the least helpful comment I have seen this month. You also force closed the post. Really? If you don't want to help then don't bother.

**Comment by NoShotz** [comment]
The best place to look for help is the [subreddit](https://www.reddit.com/r/HaloOnline/), the GitHub is meant for issues with the code as said above. If you were to post on the bi weekly thread on the subreddit, you would get answers there, more people view that.

**Comment by scooterpsu** [comment]
I'm not sure if you're familiar with something like GitHub, but every comment on these goes to everyone "watching" the project. Each message here emails 60 people. It is not a conclusive method for debugging a specific user's issue. We have these other communication methods in place for exactly this reason.
