### ISSUE TITLE
VoIP-Chat | Joining a full game.

### ISSUE THREAD

**Issue by DArkes1312** [ElDewrito/ElDorito#22]
When you're joining a full game ( 16/16 ) by the server browser, the game won't connect to it ( that normal ) But the gamechat and voIP will join.

Oh, and when I joined the game when someone left, I got the voices two times and my nick was Herthes1

When I left the game and joined another one, the voIP wasn't working anymore ( couldn't talk/ear peoples. )

**Comment by dark-c0de** [comment]
My bug. I'll fix it!
