### ISSUE TITLE
Backing out of a lobby doesn't always allow players to change active player.name

### ISSUE THREAD

**Issue by scooterpsu** [ElDewrito/ElDorito#225]
Need to _always_ be able to change active player.name outside of a lobby. Currently only changes before entering a lobby, and sometimes not even then.

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Play game, back out to main menu

2. Change player.name

3. See old player name in next lobby

**Comment by medsouz** [comment]
Fix caused issues and had to be reverted
