### ISSUE TITLE
Duals Appearing on Wrong side If Started with Duals.

### ISSUE THREAD

**Issue by PersonalityPi** [ElDewrito/ElDorito#226]
### What were you trying to do before the issue occurred? 
Attempting to pick up a dual when starting with a weapon that could be dual'd
### What happened?
Wrong widget appeared on the right side instead of the left side.
### What did you expect to happen?
Widget should have appeared on the left side with correct key.
### How can the issue be reproduced?
Please be as descriptive as possible.

1. Start a Game with a Duals gun set as the main weapon (For example, Smg).
2. Attempt to pick up a weapon that can be dualed ingame.

**Comment by unk-1** [comment]
Fixed. See 1f295d5cccd6447a3e253b0d9c69deea0670f5d7
