### ISSUE TITLE
enabling/disabling vsync requires a restart to take effect

### ISSUE THREAD

**Issue by HaloonlineJ** [ElDewrito/ElDorito#228]
### What happened?
vsync must be turned on in most cases to fix the micro-stuttering, but many players don't realise they need to restart the game and think they're experiencing fps issues. 

### Solution
when enabling or disabling vsync, prompt the user with a *Requires a restart to take effect* message.

**Comment by scooterpsu** [comment]
Prompt added in 353a10631bbbb2527f463465a68719bbe8251a67
