### ISSUE TITLE
Missile Pod reticle doesn't turn red when locked on

### ISSUE THREAD

**Issue by Willpower719** [ElDewrito/ElDorito#229]
### What were you trying to do before the issue occurred? 
Trying to lock on to someone with the missile pod
### What happened?
The game plays the beeping sound while it is locking on and a different set of beeps when it is locked on.
The game does not however turn the reticle red when locking on or the add the little red box when it is locked on.
### What did you expect to happen?
I expected both the sounds to play and the reticle turn red
### How can the issue be reproduced?

1. Get the missile pod

2. Have another player get in a vehicle

3. Aim the missile pod at the vehicle

4. Look at the blue reticle

**Comment by Alex-231** [comment]
I fixed this one a while ago but lost the file. Ill sort it again.

**Comment by Alex-231** [comment]
![fix demonstration](http://i.imgur.com/I38lfns.png)

Fixed. Will include in next tag fix bundle.
