### ISSUE TITLE
Controller sensitivity seems to control acceleration

### ISSUE THREAD

**Issue by Clef-0** [ElDewrito/ElDorito#231]
Testing 0.6 - the controller sensitivity does not function how it did on the Xbox and seems to affect acceleration speed rather than actual sensitivity. According to Willpower, this started in 0.6.

**Comment by lafloor** [comment]
probably not 0.6 dependent; the higher sensitivities (8, 9, 10) are practically unplayable on 0.5 because of the acceleration, seems like a saber thing.

**Comment by scooterpsu** [comment]
Partially duplicated in #257, so I'm going to close this one since that's more comprehensive.
