### ISSUE TITLE
On the "Halo Reach Default" controller layout, sprinting over a dualable weapon stops to pick it up

### ISSUE THREAD

**Issue by Clef-0** [ElDewrito/ElDorito#233]
0.6 - setting controller layout in web ui settings, tested with 360 controller and PS3 controller (using ScpToolkit). might be related to input priority or the lack of distinction in controller button binding command between button press or hold

**Comment by Alex-231** [comment]
I think I know what's wrong with it. I'll have a look.

**Comment by Clef-0** [comment]
Binding dual wield to B has no conflicts (switch grenades and dual wield coexist happily), so it's my opinion that B should be the default Reach layout bind.

A similar issue exists with Halo 3's default layout where Sprint is assigned D-Pad right and is not easy to use without the sprint toggle enabled.

**Comment by scooterpsu** [comment]
Moved to B in c335669189077a60dcc39b5c12d6c4c692b3fc74. Worth revisiting after binds allow a separation between press and hold.
