### ISSUE TITLE
Console doesn't open on rare occasions 

### ISSUE THREAD

**Issue by PersonalityPi** [ElDewrito/ElDorito#249]
### What were you trying to do before the issue occurred? 
Attempting to open the console.

### What happened?
it doesn't open.

### What did you expect to happen?
It to open.

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Open game.
2. Attempt to Open Console.

**Comment by num0005** [comment]
The CEF overlay breaks if you have multiple  game processes open at once because it can't lock the temp directory or something like that.

**Comment by medsouz** [comment]
The issue has been reported happening by people running a single instance of the game.
