### ISSUE TITLE
Spectating Issues  

### ISSUE THREAD

**Issue by PersonalityPi** [ElDewrito/ElDorito#261]
### Information
1. Spectating is appearing in Slayer Modes.
2. Spectating is showing instant switching to other players when entering spectating apon death.

### 1. What were you trying to do before the issue occurred? 
Playing a round of slayer.

### 1. What happened?
When dying in slayer modes I was able to spectate the other players.

### 1. What did you expect to happen?
The spectating to remain on my death body with no player card.

### 1. How can the issue be reproduced?
1. Play a match of slayer.
2. Die and look at the spectating overlay.

### 2. What were you trying to do before the issue occurred? 
Playing a round of team slayer.

### 2. What happened?
When dying the spectating instant switches to another player.

### 2. What did you expect to happen?
The spectating to remain on my dead body till switched.

### 2. How can the issue be reproduced?
1. Play a match of team slayer.
2. Die and look as the spectating overlay.

**Comment by unk-1** [comment]
Fixed 101e06a3acaec1305f77090f44383df698570719
