### ISSUE TITLE
Camera.HideHUD fails to hide the HUD and distorts it while in vehicles

### ISSUE THREAD

**Issue by PlGGS** [ElDewrito/ElDorito#269]
I am using the most recent developer build as of 8/27/17 and have no mods installed.

### What were you trying to do before the issue occurred? 

Mess around in the console.

### What happened?

I disabled the HUD with Camera.HideHUD and then got in a vehicle.

### What did you expect to happen?

The HUD to stay hidden,

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Open the console

2. Type Camera.HideHUD

3. Already be in/get into a vehicle(or by picking up a turret)

**Comment by Alex-231** [comment]
Fixed as of f1dccc81743f92ce8330f2b42344d3d712f0864a.
[Video](https://www.youtube.com/watch?v=feB8WCb1qMM&feature=youtu.be)
