### ISSUE TITLE
The overlay speaking players display list shows duplicate players, and is always active.

### ISSUE THREAD

**Issue by Alex-231** [ElDewrito/ElDorito#274]
The speaking players list shown in game sometimes lists duplicate players.
Additionally, the overlay is still shown when the player chooses to use the HUD display instead, when it should be hidden.

![image](https://user-images.githubusercontent.com/11706994/30005494-c7c28bda-90db-11e7-98dc-519729c55da8.png)

**Comment by maximumgame** [comment]
Fixed in a28fc384d8a877b9510a1398941d95a9b80ae071
