### ISSUE TITLE
Take Screenshot doesn't work while in Settings UI.

### ISSUE THREAD

**Issue by PersonalityPi** [ElDewrito/ElDorito#280]
### What were you trying to do before the issue occurred? 
Take a screenshot while in settings UI.

### What happened?
Nothing happened.

### What did you expect to happen?
A screen to be taken while in settings menu when pressing the bind.

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Navigate into Settings UI.
2. Attempt to take screenshot.

**Comment by Willpower719** [comment]
The screenshot function is built into eldorado and only captures the game window. It doesn't capture any overlays such as cef.

**Comment by soular00t** [comment]
Willpower is correct, however to bypass this, you would simply use alt+prntsc
tho not as useful, i dont see another workaround for this anytime soon.

I asked ale for the screenshot action to work similarly to Bungie's screenshot system for a fileshare setup (as it does write its own special data to the file). In theater you could take clips and create an image from that. Basic idea, is to be in-game for the screenshot, so UI menus etc shouldnt really be present anyway. Using reshade wont work either i dont think, as it adds it's own layer to the game. So only legit images would be allowed, editing the image through an editor also alters the content header, and will deny upload/download request through fileshare overlay.

**Comment by medsouz** [comment]
The screenshot function needs to be moved to run after the CEF EndScene hook.

**Comment by medsouz** [comment]
Resolved by #300

**Comment by HaydnTrigg** [comment]
@medsouz Upon testing, it appears this issue has been resolved.

**Comment by scooterpsu** [comment]
Actually fixed in 1d6ba181cc8bfd25dc9bbc4b5b946b32fb4e6236
