### ISSUE TITLE
Chatbox text being cut off if your in-game name has no descender letters

### ISSUE THREAD

**Issue by HaloonlineJ** [ElDewrito/ElDorito#283]
Outline of bug:
the chatbox only renders/scrolls as far as the lowest point of your in-game name, resulting in letters that descend below the baseline being cut off.

example: http://imgur.com/a/cI2Yl

**Comment by scooterpsu** [comment]
Should be fixed with ab7331471b9ad187ed52ff4d3256250b0b4e09e3
