### ISSUE TITLE
Dedicated servers no longer work

### ISSUE THREAD

**Issue by jaron780** [ElDewrito/ElDorito#284]
### Guidelines
- Your title should clearly describe the issue.
- Describe the exact steps you took before the problem arose.
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link).

### What were you trying to do before the issue occurred? 
Updating dedi to latest commit

### What happened?
nobody could connect to the dedi

### What did you expect to happen?
let people join

### How can the issue be reproduced?
Please be as descriptive as possible.

1.  Apply latest commit from github to dedi

2. Start server

3. Try to join the server

### Additional info
It seems to act the same way as the dedi bug except 100% of the time. Rebooted server and vm many times and still wouldnt connect, downgraded to older appveyor build and i was able to join without issue. Could be caused by one of rabids latest dedi server commits and no errors in dorito.log

**Comment by RabidSquabbit** [comment]
Fixed by commit 64e8babbc6b1dd1dd082cf2f3b918172c6d46433
