### ISSUE TITLE
Pressing F6 repeatedly crashes the game

### ISSUE THREAD

**Issue by Highlander1536** [ElDewrito/ElDorito#285]
### What happened?
Pressed F6 repeatedly crashed the game to a error.

### What did you expect to happen?
It not to crash the game.

### How can the issue be reproduced?
Pressed F6 repeatedly.

**Comment by Clef-0** [comment]
Call stack for that bug: https://i.imgur.com/UjJPLPT.png

**Comment by Willpower719** [comment]
This only happens in -debug builds and when starting the game with -webdebug. F6 refreshes all of the cef menus and spamming it overloads cef

**Comment by scooterpsu** [comment]
Like @Willpower719 said, this is only in debug builds or using the -webdebug flag.

My recommended "fix" is to not spam the F6 key unless you're using a release build, then you can spam whatever key you like.
