### ISSUE TITLE
Can't join about half of games, just returns to lobby

### ISSUE THREAD

**Issue by jordlynn** [ElDewrito/ElDorito#296]
### Guidelines
- Your title should clearly describe the issue.
- Describe the exact steps you took before the problem arose.
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link).

### What were you trying to do before the issue occurred? 
Joining any game.

### What happened?
Server browser exits to main menu in game.

### What did you expect to happen?
Join a game.
### How can the issue be reproduced?
Please be as descriptive as possible.

1. Try and join game via double clicking

## Troubleshooting

I've tried opening ports that are associated with servers, had no effect.

Try joining servers with all kinds of ping, had no effect.

Additionally I have a friend that lives in another 'region' and he sees similar effects, both on the same servers and different ones. I would say 75% overlap in the servers that we can't join, 25% unique.

**Comment by PersonalityPi** [comment]
Dedi bug. Fixed in next update.

**Comment by scooterpsu** [comment]
This is fixed in 0.6, which is still on track to be released by the end of the month.
