### ISSUE TITLE
Add command to trigger Alert Carry pose

### ISSUE THREAD

**Issue by scooterpsu** [ElDewrito/ElDorito#297]
Since it's possible with a controller, but not easy with a keyboard, a command that could be run/bound to a key would solve this.

I'd suggest `Player.AlertCarry 1/0`.

**Comment by theTwist84** [comment]
I started this 3 hours ago by repeatedly using the halo 3 button combo and checking cheat engine and now I have a fully working implementation of the command with thanks to @medsouz and @Ernegien for pointing out obvious stuff I was oblivious to. https://gist.github.com/theTwist84/524320fb0125c6f05ad9ab2b5707067f

**Comment by theTwist84** [comment]
Implemented in 800441f61724fc84293fc441d0f8893166d3274b
