### ISSUE TITLE
Where is news about this posted now?

### ISSUE THREAD

**Issue by Icarus77** [ElDewrito/ElDorito#3]
There used to be a /halopc/ on 8ch where people discussed this and there was a development general.  It's been dead for a couple of months, but I just found out that this is still being updated rather frequently...  Can a dev give a short summary of the progress made since April, and maybe say where I can follow the development of this?

**Comment by Fablock** [comment]
Hi! not a dev but there is a subreddit and a IRC channel for the project.
links: 
Subreddit: https://www.reddit.com/r/HaloOnline/
IRC: http://irc.lc/snoonet/eldorito/

**Comment by Eryla** [comment]
[/r/HaloOnline](https://www.reddit.com/r/HaloOnline/)
or IRC.

**Comment by emoose** [comment]
Yeah we mostly communicate on reddit and IRC (http://irc.lc/snoonet/eldorito/), I also have a twitter where I post updates about ED: https://twitter.com/_emoose_

It's too bad the Halo Online generals and such died, they were fun.
