### ISSUE TITLE
Gunfire Lag in high volume firefights

### ISSUE THREAD

**Issue by l33tLumberjack** [ElDewrito/ElDorito#302]
### Guidelines
- Your title should clearly describe the issue.
- Describe the exact steps you took before the problem arose.
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link).

When playing on a server with a lot of other players and you get into a smallish area with a lot of people firing the audio for your weapon begins to lag behind you actual firing rate. Eventually your weapon will not play its audio at all until you step away from the fight or respawn.

### What were you trying to do before the issue occurred? 

Just play normally.

### What happened?

While playing on a high volume server I noticed the audio for my Battle Rifle was either playing seconds after I shot or not at all. This is also notable with the Sniper Rifle when firing at a faster rate as it seems the audio file is longer than the minimum time between shots. The effect of this is the same as above.

### What did you expect to happen?

I expected the weapon to play its audio file when it fired every time.

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Log into a higher volume server and get into a large firefight in close proximity to reproduce this issue

**Comment by NoShotz** [comment]
The sound lag is fixed in 0.6.

**Comment by medsouz** [comment]
Fixed in https://github.com/ElDewrito/ElDorito/commit/8e40f27879607337c77b89f0e1afa875013bd5b4
