### ISSUE TITLE
Certain CEF menus fail to load

### ISSUE THREAD

**Issue by KamakaziePidgeon** [ElDewrito/ElDorito#306]
### What were you trying to do before the issue occurred? 
Load up a release/dev build
### What happened?
Sometimes certain (not all) CEF menus fail to load. Mostly the settings menu & loading screen fail but I've experienced it with the ingame chat too. Had the issue occur on two different machines.
### How can the issue be reproduced?
Please be as descriptive as possible.

1. Load the game

2. Look out for the fade in or ED splash loading in.

3. Try load a map, see if the loading screen appears.

**Comment by scooterpsu** [comment]
Fixed with 559b411e3f6d86b855bfb5fa8f4667786c494bc5
