### ISSUE TITLE
Unable to use spaces when setting server name in server settings

### ISSUE THREAD

**Issue by num0005** [ElDewrito/ElDorito#315]
### What were you trying to do before the issue occurred? 
set server name
### What happened?
server name was not escaped and it was cut off after the first space
### What did you expect to happen?
for the server name to be set correctly
### How can the issue be reproduced?
Please be as descriptive as possible.

1. start lobby

2. open server settings

3. try to set the name

**Comment by num0005** [comment]
Update: it seems to also happen with other strings

**Comment by theTwist84** [comment]
mods\ui\web\screens\server_settings\settings.js 
Changing line 87: `dew.command(result[1]+' '+newValue);` to `dew.command(result[1]+' \"'+newValue+'\"');` will fix this

**Comment by scooterpsu** [comment]
Fixed in 84cbb1979f1dbc1b3aa34ad2b93bee6768ba742b
