### ISSUE TITLE
Choosing PWR Plasma Pistol in game options doesn't work 

### ISSUE THREAD

**Issue by Dava96** [ElDewrito/ElDorito#328]
### What were you trying to do before the issue occurred? 
Changing Gametype settings

### What happened?
When Choosing Primary weapon, it doesn't let you chose PWR Plasma Pistol, It just reverts to default.

### What did you expect to happen?
To be able to choose that weapon.

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Go into Gametype settings in a Lobby.

2. Change the Primary (or any weapon selection) to PWR Plasma Pistol

3. The Game doesn't allow you to select it.

**Comment by jabukufo** [comment]
Fixed

**Comment by soular00t** [comment]
Does this effectively remove the ability to use weaponless gamemodes?
