### ISSUE TITLE
Balance Turret (attached, detached, and warthog) by reducing damage or rate of fire to be more in line with Halo 3

### ISSUE THREAD

**Issue by Jamonnin3** [ElDewrito/ElDorito#341]
### What happened?
The turret's shoot much faster than in Halo 3 and are not balanced as a result. I'm not sure if they shoot faster or do more damage or both.

### How can the issue be reproduced?
The Pit and Last Resort turrets (attached and detached). Warthog on Icebox, Valhalla, Standoff, etc.

1. The turrets have more damage per bullet, or shoot more bullets per second, or both.

2. The turrets are not balanced whether attached, detached, or on a warthog.

3. Please balance the turrets, thank you. 👍

**Comment by NoShotz** [comment]
The weapons have already had their damage modified to be their halo 3 stats in 0.6.
