### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ThatOneEdgelord** [ElDewrito/ElDorito#348]
Hey inwas getting an issue saying i was missing the file d3dx9_43.dll please help

**Comment by NoShotz** [comment]
This is the wrong place to ask for help with this kind of issue, the GitHub is for code related issues, you are just missing the required DirectX version. Please run the files in the TPI folder, one of the installers is a silent installer, so just give it a bit.

**Comment by medsouz** [comment]
Install DirectX 9

https://www.microsoft.com/en-us/download/details.aspx?id=35
