### ISSUE TITLE
Cannot Close Halo 3 Voice Communication Menu

### ISSUE THREAD

**Issue by pkillboredom** [ElDewrito/ElDorito#351]
### What were you trying to do before the issue occurred? 
Navigating Halo 3 Menus on a build of 0.6 (without tags).

### What happened?
Became unable to close the Voice Communication menu without Alt-F4.

### What did you expect to happen?
The ability to exit this menu with Escape or Backspace.

### How can the issue be reproduced?

1. Start any Multiplayer or Forge game.

2. Press Esc.

3. Navigate to Settings -> Voice Communication and press enter
![eldewrito__version_0 6 0 0-debug__build_date_n_2017-11-12_23-08-04](https://user-images.githubusercontent.com/4422110/32709524-0e0e78f6-c7ff-11e7-9a8b-323527268cce.jpg)

**Comment by NoShotz** [comment]
i'm pretty sure this is not an issue with the proper tags.

**Comment by pkillboredom** [comment]
Oh cool, thanks.
