### ISSUE TITLE
When damage=0%, physics from grenades only applies to host's vehicle

### ISSUE THREAD

**Issue by LyamWitherow** [ElDewrito/ElDorito#354]
For some reason, while playing with just a few people on a custom forge map (crates in sky with warthogs, bumpercar style), only the host can be affected by grenade explosions. If anyone tries to nade a stationary vehicle, no physics is applied to it.

- Using Ver 0.5.1.1

Steps to re-create:
1) Set player damage to 0%, enable invulnerable vehicles
2) Have client get in warthog, and host sticky the warthog.
3) No physical force is applied to the warthog.
4) Have host get in warthog and have guest sticky the warthog
5) Physical force does effect the warthog.
6) Guest or host try to sticky warthog with no one in it
7) No physical force is applied to the warthog.

Unfortunately I can't really test beyond what I'm experiencing.

**Comment by NoShotz** [comment]
Fixed in 0.6.

**Comment by LyamWitherow** [comment]
Fantastic! Sorry for the waste of time, I couldn't find any notes about it being fixed.
