### ISSUE TITLE
Multiplayer doesn't work

### ISSUE THREAD

**Issue by TheAwesome150** [ElDewrito/ElDorito#358]
I downloaded ElDewrito yesterday.
The only thing i can play is Singleplayer Forge.
I cant even select the Multiplayer Server button (its grayed out, pressing space does nothing).
My PC is connected to the internet. And i tried refreshing it.
Thanks for understanding

**Comment by NoShotz** [comment]
When you press space on it, the server browser will open in the background, likely behind the game window.

**Comment by scooterpsu** [comment]
Please use the [Discord](https://discord.gg/halo) for actual debugging of your copy of Halo Online. This is for issues with the ElDewrito mod itself.
