### ISSUE TITLE
21:9 resolutions make the hud small.

### ISSUE THREAD

**Issue by formatme** [ElDewrito/ElDorito#366]
As someone asked on the reddit weekly questions, 
"I am noticing a HUD glitch when playing on a 21:9 monitor. The HUD elements are set to the size of a smaller monitor. Is there a simple mod I can install to fix this or is there no fix yet. See the images below. https://imgur.com/a/kKLY4"

I personally also would like to see support for 21:9 resolution, more and more people are using it.

**Comment by Alex-231** [comment]
I believe this is fixed in 0.6 already and I think it only affects some custom HUDs. I'm going to be looking into HUD resolution again at some point as I think we can handle ultra wide resolutions better, but for now I'd recommend trying the normal HUD. If that doesn't work please let me know.

**Comment by ToonByte** [comment]
It might a resolution thing as my game doesn't have that issue.  My monitor is 2560x1080 https://i.imgur.com/YrlgRF3.jpg

**Comment by Alex-231** [comment]
It's probably just because you're using the default HUD rather than the halo 3 HUD.

**Comment by scooterpsu** [comment]
This appears to be an issue with the Halo 3 hud and not the default Halo Online hud, so it's a mod issue and not an ElDewrito issue.
