### ISSUE TITLE
Problem selecting 'default' FOV in the in-game menu presets

### ISSUE THREAD

**Issue by HaloonlineJ** [ElDewrito/ElDorito#379]
### What were you trying to do before the issue occurred? 
Swapping between FOV presets in the in-game menu

### What happened?
I tried going back to Halo Online 'default' FOV by selecting it and confirming, but it stays on the last chosen FOV preset.

### What did you expect to happen?
For it to revert to the Halo Online 'default' FOV

Example:
https://gfycat.com/RepentantCavernousCurlew

**Comment by NoShotz** [comment]
Was really confused at first, considering there are no FOV presets, these are viewmodel configs.
