### ISSUE TITLE
Question about a possibly unnecessary file found.

### ISSUE THREAD

**Issue by SC1040-TS2** [ElDewrito/ElDorito#381]
This isn't so much a problem as it is a question.

While I was looking around the game files, I found two Direct3D HLSL compilers right next to one another, as follows.
1. d3dcompiler_43.dll (Properties description lists it as Direct3D HLSL Compiler, version 9.29.952.3111, 2.00MB in size. Signed May 21, 2010 in SHA1.)
2. d3dcompiler_47.dll (Properties show it as Direct3D HLSL Compiler for Redistribution, version 6.3.9600.16384, 3.30MB in size. Signed August 22, 2013 in SHA1 and SHA256.)

I was curious about whether the former of the two HLSL Compiler redistributables was actually needed to play the game given the superficial implication that it was an older, and therefore unnecessary .DLL file, so I moved it outside of the game's folder and ran it to see if anything would crash.

What I found was a bit surprising. Not only did I find that the game could still play as normal, but I could arguably find no difference in performance with or without the former compiler. While I have yet to do any further testing, I am wondering if the older redistributable is safe to remove, and whether or not it should be.

Note that my version of ElDewrito is the current stable version of 5.1.1. Only the first compiler residtributable's directory path is changed in my current testing.

Regards,

—TS2

**Comment by medsouz** [comment]
Those DLLs are a dependency of CEF. 

They may also exist in your C:\Windows\System32 directory as part of your DirectX installation which would explain why it still works after deleting them.

**Comment by SC1040-TS2** [comment]
Thanks for clarifying, @medsouz. Both compilers do indeed exist as part of my System32 directory. I presume these are included within ElDewrito if they do not exist on the system as a precautionary measure, or to allow for software rendering instead of pulling from the system directory which may or may not include the same compilers, thereby breaking the game upon startup?

Do note that I'm not familiar with CEF and how its dependencies operate, so I can't say for sure if one is needed over the other. I will test to see if removing the System32 compiler from its directory breaks the game or otherwise causes issues with it, however, as a test to see if the game can still run reasonably run without any D3DCompiler_43.dll dependency to call to in the default folder paths.

**Comment by SC1040-TS2** [comment]
Wait, hang on, after doing some research, I finally found what each one was.

The former compiler is or could be a DirectX9 implementation, though its version number is an odd one compared to known releases of the API, whereas the latter, more recently published compiler is a direct implementation of DirectX11.2. Its version number matches the one I could find on Wikipedia, and I haven't found much else to support this conclusion, so perhaps that may be it.

Though, I do wonder of OpenGL can be ported to the engine or not despite its DirectX dependencies and such. Perhaps it'd be best saved for another Issue.

**Comment by NoShotz** [comment]
OpenGL can not be implemented as we do not have the source code for Halo Online.

**Comment by scooterpsu** [comment]
While we appreciate the effort, questions along these lines are probably best posed via Discord (linked on the main page). This isn't an _issue_, and this conversation emails everyone watching the project (90 people currently).

Thanks

**Comment by SC1040-TS2** [comment]
I tried the Discord link once, but it does not seem to work when tried on the mobile app. It may have expired, unfortunately, which was why I resorted to posting here, @scooterpsu .

Thank you for clarifying that, by the way, @NoShotz .
