### ISSUE TITLE
[Question] Engine reimplementation

### ISSUE THREAD

**Issue by MayeulC** [ElDewrito/ElDorito#390]
Pardon me if GitHub isn't the right place for it, but it seemed like the most appropriate place to ask, while documenting the answers.

Is a complete engine reimplementation out-of-scope for this project? I can certainly get it being the case for now, but I imagine that as the project moves along, you will fight the existing engine more and more, and hacks can only get you so far...

If I understood correctly, you are already planning to completely replace the in-game menu with a custom one.

I did not find a whole lot of high-level documentation on the project (maybe I just looked in the wrong place?), but I imagine that you are already using DLL injection into the original engine to make it work the way you want. Thus, you probably already re-implemented some chunks of the engine (networking, matchmaking, etc).

So, why stop here? I would like to see is this approach used for bigger parts of the engine. For now, there seems to be (I didn't look at the code, so that's a guess):
* Network code (matchmaking)
* Main menu (pending)/Ingame menus(?)

It seems to me that replacing a few other parts could be of some use pretty quickly:
* Assets loading (it even gives you freedom to tamper with the format, and add more stuff)
* Gameplay mechanics (to make more game-changing... changes). This includes:
  * Physics -- collisions, etc
  * Gameplay rules, scoring, victory conditions...
  * Spectator mode improvements
* Input handling
* Graphics engine (this is probably a big piece, but I imagine there are some enthusiasts out there). This would be nice to offer even more tweaks.

And all the other stuff that probably sits in-between.

As a bonus, since you already have compiled code, writing new functions to be an exact match (same input, same output) to be a drop-in replacement could make this faster. Once you have it, you can expand their scope. The hardest part is probably to match in-memory data structures, and to keep ABI compatibility -- some midlayers could be used to make the code cleaner.
My analysis might be incomplete, as I wasn't able to launch the game under wine (it just sorts of hang in the first intro video). One of the benefits could be ports to more platforms (ooh, just imagine running this on a raspberry pi once the last bit of original binaries is shed -- OK, maybe not a pi, but you get the idea).

Of course, I apologize if that's already part of the master plan ;)

In part II, replacing stock assets with community-made ones sounds like something that could be done to make the game a lot less murky ;)

**Comment by dany5639** [comment]
You should join our Discord for a more appropriate discussion www.discord.gg/halo

**Comment by MayeulC** [comment]
Well, I asked here so that the answer could be publicly viewed/searched, and I must say that I would be a lot happier to use a more open alternative to discord, such as matrix, but I'll consider it :wink:

**Comment by scooterpsu** [comment]
In simple terms, yes. **Way** out of scope. While parts of this mod are modifying the engine, rebuilding the engine from scratch would be a drastic undertaking. The engine we have is directly responsible for the game playing the way it does.

Also while I understand the idea of using this as a place to pose an open question, discussion here leads to emailing everyone following the project (90 people currently).

Discord is the best method for getting in direct contact with the team and the community. Feel free to ask any questions there.
