### ISSUE TITLE
Unable to join dedicated servers

### ISSUE THREAD

**Issue by kaysond** [ElDewrito/ElDorito#401]
### What were you trying to do before the issue occurred? 
Join a dedicated server

### What happened?
Server browser closes, but game doesn't join the "party"

### What did you expect to happen?
Join the party on the dedicated server and launch the game

### How can the issue be reproduced?
1. Launch game

2. Press <Enter> on server browser

3. Click on a dedicated server

I've tried these and they don't work:
[US-Midwest] G-Money's House of Honey's - 8v8 - Dedicated #2
[US-EAST] Halo Online - 24/7 Snipers 6v6 - Dedicated - #5
#5 [US-WEST] Dedicated Community FATKID & SKYCASTLE Server

I've heard this should be fixed in 0.6, but wondering if there's a workaround in the meantime

**Comment by jaron780** [comment]
What you are getting is probably the Dedi bug. You will need to try to change your "LOCAL" ip and it might fix it. Otherwise just wait or join the servers when they are empty and join then. If you still cant joijn you might be banned and need to contact the host.

**Comment by scooterpsu** [comment]
This is the biggest bug that exists in 0.5.1.1, but the true fix is waiting on the update. If you need help changing your local ip to see if that fixes it, please use the Discord.

**Comment by kaysond** [comment]
What should I change it to?

**Comment by scooterpsu** [comment]
Please use the Discord for support on 0.5.1.1. Every post here emails everyone watching the project, which is up to 100 people now.
