### ISSUE TITLE
Suggestion. aim assist toggle / aim magnetism toggle

### ISSUE THREAD

**Issue by james-munson** [ElDewrito/ElDorito#404]
The feeling of aiming gets ruined by the magnetism or what ever it is. It would be nice for servers to toggle it or the client. I would love if the aiming was nice and smooth like csgo.

**Comment by NoShotz** [comment]
Having it off on the whole server will prevent controller users from playing on that server

**Comment by james-munson** [comment]
So, let there be servers for only controller users than? or server owners could put "Mouse /KB only" or " Mixed controller " or something in the title

**Comment by james-munson** [comment]
Hope this is still a priority, a dev said this years ago and there is still this magnetism
"Going to be honest here, this has been a huge priority for us from the start but we just don't know where it's coming from. The code in the game for handling mouse input is rather complex and full of floating-point operations which are hard to decipher. There's a mouse acceleration option in the settings but it doesn't seem to affect much. We're trying to remove it and we understand it's a huge issue, believe me, but unfortunately we can't really guarantee anything."

**Comment by theTwist84** [comment]
@james-munson please use discord for any suggestions as having this conversation here is emailing over 100 people including myself.

**Comment by james-munson** [comment]
@theTwist84 someone should make a suggestions channel on the discord c:
