### ISSUE TITLE
HypeOverflowError on Launch, sometimes even when I just think about the game

### ISSUE THREAD

**Issue by JakeRunsDnD** [ElDewrito/ElDorito#416]
### Summary
I cannot contain my hype because you are amazing devs doing an amazing thing and I haven't felt this excited about a game since Halo 2

### What were you trying to do before the issue occurred? 
Live without Halo as a PC nerd I guess, sob story really

### What happened?
I saw the light

### What did you expect to happen?
Something something burst into flames

### How can the issue be reproduced?
Please be as descriptive as possible.

1. I found the light that is eldewrito

2. I played infection and swat and it was glorious and I lost my collective 💩 

3. .....and it's being UPDATED!??!!?

4. Happiest I've been about anything gaming related in a VERY long time

### Side note
To be ultra clear there is no issue, you guys are amazing and deserve some hype in the backlog to offset the crazy final push you're probably making for the 0.6 release. You rock, and you make the world a better place

**Comment by medsouz** [comment]
Please don't spam our issue tracker, it sends an email to the 104 people currently watching the project.

Keep the hype contained to Discord or Reddit!
