### ISSUE TITLE
Main menu music doubles

### ISSUE THREAD

**Issue by brodycas3** [ElDewrito/ElDorito#419]
Just idle at the main menu and it will start to play double music.

I like the music but not that much.

**Comment by NoShotz** [comment]
if you are using a server browser like thefeeltrains browser, that will happen, you will have to disable his browsers music.

**Comment by brodycas3** [comment]
err, I'm currently using the scooter menu.

**Comment by brodycas3** [comment]
It also starts and stops while in game.
