### ISSUE TITLE
Controller input captured by Chat view while in game

### ISSUE THREAD

**Issue by xp499** [ElDewrito/ElDorito#424]
What were you trying to do before the issue occurred? 
To play a match while typing in chat using controller

What happened?
Player stopped moving because controller input was captured by chat view. In 0.5.1.1 this worked simultaneously. 

What did you expect to happen?
As i am a huge fag, i have the skill of continuing playing while i'm typing (LOL). So i expected to keep playing as while typing. This was working as intended in 0.5.1.1

How can the issue be reproduced?
To type while in game and try to keep play with controller.

**Comment by theTwist84** [comment]
This is how chat is intended to be, in 0.5.x it was a bug and the dev who implemented it went MIA and it was never fixed

**Comment by xp499** [comment]
Will you be typying with a controller then? LOL

**Comment by NoShotz** [comment]
If you have a chat pad, yes.

**Comment by Red-M** [comment]
I might be if I want to go back to a controller :)

![img_20180422_010742](https://user-images.githubusercontent.com/1468433/39085716-1c3c6a02-45ca-11e8-8a0c-a3c811acfbaa.jpg)
