### ISSUE TITLE
Unable to Join, timed out

### ISSUE THREAD

**Issue by SwordedGun** [ElDewrito/ElDorito#429]
So, I've been trying to play this game for the last year or so, but never managed it because when I clicked on a server it would simply not join me to it. Couple of days ago I managed to get into a couple of games and play them without any problems, but then it just stopped working and i've been stuck with the same problem ever since. Anyone knows how to fix this?

**Comment by scooterpsu** [comment]
A couple days ago was before we released 0.6, which just happened yesterday. What you're describing is a bug we fixed. Go to http://reddit.com/r/HaloOnline to get the update.

**Comment by SwordedGun** [comment]
I've installed the 0.6 this morning and wasn't able to join any games, no matter what server
