### ISSUE TITLE
Spawnpoints don't show up when loading up a forged map

### ISSUE THREAD

**Issue by Dead-Pixel-Entertainment** [ElDewrito/ElDorito#436]
I'm on 0.6, got the build from the subreddit. 
I made a map on Forge, played it in multiplayer, had to go back and edit some things and then I noticed the spawns had vanished from forge. The game acted like they were still there, but there is no way to edit or delete them now.

**Comment by NoShotz** [comment]
You need to make sure the spawns are set to the proper gametype in the gametype setting within the object properties UI.

**Comment by Dead-Pixel-Entertainment** [comment]
Thanks for the fast reply. I set down spawns for infection, but I can't find anyway to launch forge in infection to edit the spawns

**Comment by NoShotz** [comment]
you don't need to, press X on the spawn, click the button that says gametypes, and choose the gametypes you want it on.

**Comment by Dead-Pixel-Entertainment** [comment]
![screenshot-2018 04 21-23 51 39](https://user-images.githubusercontent.com/16175301/39089441-f734b698-45be-11e8-818b-587516776bcf.jpg)
I have placed a spawn right there, then saved the game and reloaded the map in forge. There should be a spawn right there but I can't see it at all in forge so I am unable to press X on it

**Comment by NoShotz** [comment]
in that case, open the pause menu, and there should be a change gametype button.

**Comment by Dead-Pixel-Entertainment** [comment]
Ahhhh, thank you so much. I don't know how I missed that. Thanks for the fast response and the help. And keep up the fantastic work!
