### ISSUE TITLE
Server population/servercount 

### ISSUE THREAD

**Issue by SynthWave** [ElDewrito/ElDorito#440]
Server count/population is client side but it should known by the master server then sent to clients.

**Comment by SynthWave** [comment]
You might be able to have a secondary server that takes the data from multiple master severs and gets an accurate playercount and relays it back to either the master server(s) or clients. Seems a little unnecessary though but I've seen other developers use trees of master servers for situations like that.

**Comment by Shadowfita** [comment]
I think he's talking about the menus doing the population count individually which is slower.

**Comment by MarkIvanowich** [comment]
A metric such as server-wide population should be kept on client-side.

The data needed for the calculation is already served; why make two json requests, and add server load (expensive, fast) when the client-side can do it for you (free, albeit slow)? Having both in one request is redundant, and will just be garbage data when focused on an individual session.

Adding a secondary server solely for population metrics **is** unnecessary; can't justify the cost of hardware (even virtualized).

**Comment by scooterpsu** [comment]
The method my browser uses loads server-data incrementally (hence the speed). The data source it uses doesn't have these metrics, and therefore can't be added as-is. This is not a final solution, just holding us over until something else is in place.

This conversation is emailing 107 people per-response, so I'm closing and locking it.
