### ISSUE TITLE
Unable to spawn if player scale is too large in some default spawn locations

### ISSUE THREAD

**Issue by NullTheSecond** [ElDewrito/ElDorito#442]
### What were you trying to do before the issue occurred? 
Spawn into a new map, specifically in this instance, Sandtrap.

### What happened?
Black screen after loading into the map.

### What did you expect to happen?
Spawn into the map.

### How can the issue be reproduced?
1. Select a map.
2. Set the player scale to something like 3,000%.
3. Load into the map.

**Comment by NoShotz** [comment]
not a bug, it is intended.

**Comment by scooterpsu** [comment]
^
