### ISSUE TITLE
Finalize feature set for the updater

### ISSUE THREAD

**Issue by Limited55** [ElDewrito/ElDorito#46]
Discuss below what features should the updater have. Currently the design is this.

The updater should do everything as described below.
1. Should be only thing provided via download link on the main website.
2. Should be able to self-update itself
3. Should **not** require external dependencies
4. Should download the manifest from a remote server that is stored in a json format
5. Decompress and unpack all files

The updater should **not** do things described below.
1. Handle any game content by **any** means

Things up for discussion.
1. Configurable?
2. Allow users to skip?

**Comment by kiwidoggie** [comment]
I also think that the updater should be responsible for launching the game and ensuring that the game client is running properly before terminating, but as of now it is beyond the scope of this program. Thoughts?

**Comment by Limited55** [comment]
It's vital the user only has to run one program to check for updates and
run the game. Otherwise people will forget, we want to avoid a split
community.

**Comment by ThunderWaffle** [comment]
Since the updater will not handle game content and we want only one program to launch the game, the game itself will need to apply patches, most likely from some sort of "\patches" directory.
