### ISSUE TITLE
Inverted gamepad

### ISSUE THREAD

**Issue by KeithCu** [ElDewrito/ElDorito#467]
I used to play Halo 3 with the inverted gamepad. You supported inverted mouse, but it would be great if you supported it for the gamepad also. The game looks great but I can't relearn my muscle memory so I'll just wait.

**Comment by camden-smallwood** [comment]
Settings.InvertLook "1"

**Comment by scooterpsu** [comment]
Where you set the game to gamepad, hit A. Gamepad settings are right there.

**Comment by KeithCu** [comment]
There is no way to make this change via the in-game UI, but I went to the .cfg file and made the changes and now it works great. Thanks!!
