### ISSUE TITLE
Cant open up game

### ISSUE THREAD

**Issue by StriferZ** [ElDewrito/ElDorito#477]
### Guidelines
- Your title should clearly describe the issue.
- Describe the exact steps you took before the problem arose.
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link).

### How can the issue be reproduced?
Please be as descriptive as possible.

1. Dont know.

2. This happened 2 times before with blinkw32.dll and mtndew.dll

3.

**Comment by PersonalityPi** [comment]
Please only use the downloads provided here https://www.reddit.com/r/HaloOnline/wiki/index/download.   If you are receiving a error about a skidrow.dll that means this was a repack from somewhere else.
