### ISSUE TITLE
Finalize client feature set

### ISSUE THREAD

**Issue by Limited55** [ElDewrito/ElDorito#49]
Remember, this is supposed to set the path for all future development, with that being said you must acknowledge that this is only a beta, and most features will probably not be ready at this point.

**Comment by kiwidoggie** [comment]
Current features I wanted implemented.

Custom renderer using CEF to replace any missing menu's.
Built in server browser.
Game Lobbies.
Stat Tracking (scalable)
Ingame admin commands.

**Comment by kiwidoggie** [comment]
As brought up by gamecheat, we will need to reverse and figure out how the menu's work if we are to fully replace them. Also game-specific settings will need to be covered.

**Comment by kiwidoggie** [comment]
We will be discussing the new client http://www.worldtimebuddy.com/?qm=1&lid=2643743,5128581,5368361&h=2643743&date=2015-7-26&sln=0-2

All members be available, or you will be able to catch the cliffnotes for discussion afterwards.

@emoose @Limited55 @dark-c0de @ElDewritoDev @Ernegien
