### ISSUE TITLE
Rank/stats & emblem reset every time the game is launched (name is not changing)

### ISSUE THREAD

**Issue by euronate** [ElDewrito/ElDorito#491]
### Guidelines
- Your title should clearly describe the issue.
- Describe the exact steps you took before the problem arose.
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link).

### What were you trying to do before the issue occurred? 

I was just trying to play the game in ranked playlists. I went to halostats.click to see my profile and the following showed up: https://i.imgur.com/HTAsoTi.png

I downloaded the game from the official release post before Microsoft took action against ED. I already tried a clean install and the same issue occurs. I also run the game as administrator, but that doesn't change anything either.

### What happened?

My rank and stats still reset every time I launch the game. Proof: https://imgur.com/a/77eeK0J

### What did you expect to happen?

I expected the game to save my stats/rank...

### How can the issue be reproduced?
Please be as descriptive as possible.

1. All I have to do is relaunch the game to get a different emblem and reset stats/rank.

2. I have not changed anything in the config files.

3. I do not have any mods installed.

**Comment by homonovus** [comment]
Make sure that the eldewrito folder can be written to.

**Comment by zahti** [comment]
**STATS/EMBLEM RESETTING**
1) Press `Win + R` from desktop to open run dialog box
2) Type `%localappdata%` and then press ENTER
3) Navigate to the ElDewrito folder (...AppData\Local\ElDewrito)
4) Right-click the `keys.cfg` file and click "Copy"
5) Navigate to wherever you extracted ElDewrito and then paste that file in the root folder (the one that has the eldorado.exe application)
6) Rename the newly pasted file from `keys.cfg` to `autoexec.cfg`

Note: If you delete the `autoexec.cfg` file, you will lose your stats again.
