### ISSUE TITLE
Is it possible to run eldewrito in a web browser?

### ISSUE THREAD

**Issue by Alex-A137** [ElDewrito/ElDorito#501]
I am wondering this because i am planning to attempt to run eldewrito on a chromebook, but (hopefully) without dev mode or linux mode.

if not, then would it be possible to modify the code to be able to run in something like google chrome?

**Comment by medsouz** [comment]
Currently it is only supported to run ElDewrito on Windows. There have been some attempts to get it running in Wine but I'm not sure how successful they were. Also, your Chromebook is most likely an ARM processor and an x86 processor is required.

**Comment by Alex-A137** [comment]
i was just wondering if it would maybe become a thing in the future?

**Comment by NoShotz** [comment]
No, the game can absolutely never run in a web browser.

**Comment by Alex-A137** [comment]
K. noted, and i'll just do it myself.

**Comment by daisyUniverse** [comment]
> 

Works pretty flawlessly in wine from my experience
