### ISSUE TITLE
Research use of ingame voip

### ISSUE THREAD

**Issue by kiwidoggie** [ElDewrito/ElDorito#61]
Reduce the dependencies, if we can figure out how use what is already ingame (if it exists).

**Comment by emoose** [comment]
AFAIK our build doesn't have voip, there's settings for it but they don't work and iirc I remember hearing the official beta didn't have voip when it started neither (and our build is before the beta)

There could be some of the H3 stuff left in here though, like voice markers and text on the HUD. It'd be nice if it does have them and we could integrate our voip stuff with it.

**Comment by kiwidoggie** [comment]
Closing issue as ElDorito is currently finished development.
