### ISSUE TITLE
Custom loading screens

### ISSUE THREAD

**Issue by kiwidoggie** [ElDewrito/ElDorito#68]

**Comment by emoose** [comment]
It'd be nice if we could get the actual loading screens to work properly, DewritoDev and ihatecompvir both tried looking into this though and didn't get anywhere, I'm sure there's some way we could get them working though.

Maybe just replacing them would be easier though, we could always replace them with the "proper" screens if we wanted to.

**Comment by kiwidoggie** [comment]
@emoose see https://www.youtube.com/watch?v=qPfWVfv4sCw

**Comment by theTwist84** [comment]
This should with the web-renderer branch.

**Comment by Red-M** [comment]
eh?

**Comment by medsouz** [comment]
Implemented in 5060940da60ce052415379081f124566c73d6d84
