### ISSUE TITLE
Fix improper color palate for rendering

### ISSUE THREAD

**Issue by kiwidoggie** [ElDewrito/ElDorito#74]
As seen in this screenshot http://i.imgur.com/zoznEtI.jpg, the colors are off and need to be fixed.

**Comment by Shad0wShayd3** [comment]
Hey, couple of questions. 

You are using this on our build of Eldorito right? 

The build you're using is from the last week or so, right?

Is the problem with the whole game, or just the HTML menu?

**Comment by kiwidoggie** [comment]
Just the html menu, it is currently using the new base that I wrote, that will be pending addition to Dewrito.
