### ISSUE TITLE
Main menu patch is still broken

### ISSUE THREAD

**Issue by ElDewritoDev** [ElDewrito/ElDorito#78]
I was working on implementing chat over the game's sockets when I was running into an issue with one of my vectors getting corrupted. Turns out the code for showing the main menu is still broken. [When we call openui](https://github.com/ElDewrito/ElDorito/blob/master/src/Patches/Ui.cpp#L45) we're passing in the *address* of UIData instead of its value, causing the menu data to overflow and corrupt our global variables.

Unfortunately I tried just removing the ampersands and it made the game crash when I clicked on the Play Multiplayer button <_<

In any case, this needs to be looked into ASAP.

**Comment by emoose** [comment]
The code that's missing from HO and reimplemented in the UI_MenuUpdateHook is at 0x825E4F00 in H3E, it seems to call some allocate function to get the UIData pointer, probably not the same as the UIAlloc we call since it takes 3 args in H3E, but it does seem to be a UI related alloc.

**Comment by emoose** [comment]
H3E also seems to set some dword at 0x18 in the UIData to 1 after posting the UI message (or 5 if the stringID is 0x100A8, not sure what ID that is in HO though since I don't have any H3E stringid lists..), we should probably try doing that too.

**Comment by emoose** [comment]
Seem to have it working now in DR by doing it all in the UI_MenuUpdateHook instead of the game tick hook, also seems to have fixed the two major issues with DR (ElDorito/DewRecode#6 and ElDorito/DewRecode#7) :D

**Comment by ElDewritoDev** [comment]
Thanks, I'll work on merging it in.
