### ISSUE TITLE
Unable to leave passenger seats with controller

### ISSUE THREAD

**Issue by scooterpsu** [ElDewrito/ElDorito#79]
An oldie from the gitlab page, but since you guys have been on a roll lately I thought it might be something you could get into eldorito or DR.

No prompts to exit the warthog passenger seat or the rear of the mongoose when using a controller. Only way out is to switch back to keyboard in the settings... or die.

**Comment by Shockfire** [comment]
Fixed in 119559abaa3e6b3960305d6ec16c671034ff3be4
