### ISSUE TITLE
Stats endgame call is issuing a "GET" instead of a "POST" to master servers.

### ISSUE THREAD

**Issue by dark-c0de** [ElDewrito/ElDorito#81]
Emoose, whenever you see this, I have stats working for the master server, but dewrito is doing a "GET" instead of a "POST" on end game. The stats section of the master servers are 404'ing because they aren't looking for get requests, even if stats are set to enabled.

**Comment by emoose** [comment]
Strange, the code for it is issuing a POST and when I was testing things it POSTed fine too. I'll have to have another look at it
