### ISSUE TITLE
Invisibility overlay glitch

### ISSUE THREAD

**Issue by curiouslyExistential** [ElDewrito/ElDorito#87]
When invisibility is active, a strange visual glitch occurs that makes it near impossible to play.
**Computer specs**
Laptop model: Asus K55VD, 
Graphics card: GeForce 610m
Processor: intel core i7
OS: windows 10 home.

![glitch 1](https://cloud.githubusercontent.com/assets/5522433/9303462/21a37caa-44ac-11e5-9be0-98164f9d571f.png)
![glitch 2](https://cloud.githubusercontent.com/assets/5522433/9303463/246350fa-44ac-11e5-8372-c95b14a1f474.png)

**Comment by ElDewritoDev** [comment]
This happens if you have shadows on low. Set them to at least medium.

**Comment by curiouslyExistential** [comment]
Any idea why this happens, exactly? What about low shadows causes this behavior.

**Comment by ElDewritoDev** [comment]
No clue.

**Comment by Alex-231** [comment]
I wonder if it'd be possible to just remove or disable the low option,
