### ISSUE TITLE
In-game menu navigation double-press

### ISSUE THREAD

**Issue by curiouslyExistential** [ElDewrito/ElDorito#88]
When attempting to navigate through in-game menus using the arrow keys, the game has a tendency to trigger the event multiple times, making team switching a pain, and forge excessively annoying to use.

**Comment by emoose** [comment]
There's a fix in DewRecode for this, https://github.com/ElDewrito/DewRecode/blob/master/DewRecode/src/Modules/Patches/UI.cpp#L161
Could probably be backported to ED fine.

**Comment by ElDewritoDev** [comment]
Nice, I'll try to backport it later today.

**Comment by curiouslyExistential** [comment]
Excellent news, thanks!
