### ISSUE TITLE
Restricting special characters in player names.

### ISSUE THREAD

**Issue by Spaceyavin** [ElDewrito/ElDorito#92]
According to a person in the IRC chat, usernames are able to contain characters not on a standard keyboard. It would be easier for server operators if players could only use alphanumeric characters.

**Comment by Limited55** [comment]
I have seen a name with skulls either side of the alphanumeric part. Halo 1 allowed for unicode characters and it didn't cause too much of an issue.

Are you thinking of things like kicking?

**Comment by dark-c0de** [comment]
Fixed in @3511bdc50e913f23551987529c5a9186de8442cf
